In [2]:
import numpy as np

In [9]:
np.random.seed(42)
w = np.random.random((5, 1))

X = np.random.random((4, 5))

In [10]:
X.dot(w)

array([[1.21801794],
       [1.69464656],
       [1.04608305],
       [0.86611142]])

In [19]:
result = 0
for i in range(w.size):
    result += float(w[i] * X[1][i])
result

1.6946465556062398

In [18]:
X[1].dot(w)

array([1.69464656])

In [13]:
w[0]

array([0.37454012])

In [14]:
X[0]

array([0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258])

In [20]:
X

array([[0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [21]:
np.random.shuffle?

In [22]:
np.random.shuffle(X)

In [23]:
X

array([[0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998],
       [0.15599452, 0.05808361, 0.86617615, 0.60111501, 0.70807258],
       [0.02058449, 0.96990985, 0.83244264, 0.21233911, 0.18182497],
       [0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914]])

In [30]:
batch = np.random.choice(np.arange(X.shape[0]), 2)

In [31]:
batch

array([3, 0])

In [32]:
X[batch]

array([[0.18340451, 0.30424224, 0.52475643, 0.43194502, 0.29122914],
       [0.61185289, 0.13949386, 0.29214465, 0.36636184, 0.45606998]])

In [25]:
np.random.choice(X, 2)

ValueError: a must be 1-dimensional